### ISSUE TITLE
[Enigma] Списано

### ISSUE THREAD

**Issue by pavel-b-novikov** [IsachenkoV/nsudotnet#1]
Этот код я уже видел у Светланы Стрекаловой.
Кто у кого списал? Признавайтесь.

**Comment by IsachenkoV** [comment]
Эм, да вроде никто ни у кого не списывал.
Я пользовался тем, что Вы показывали на лекции, документацией и информацией отсюда:
https://msdn.microsoft.com/ru-ru/library/bb397867(v=vs.110).aspx

**Comment by pavel-b-novikov** [comment]
![image](https://cloud.githubusercontent.com/assets/2521412/7749026/e0697aa0-ffeb-11e4-9da1-8cfc2e84c87b.png)
![image](https://cloud.githubusercontent.com/assets/2521412/7749052/0cdef524-ffec-11e4-9780-b6510f379024.png)

![image](https://cloud.githubusercontent.com/assets/2521412/7749093/5e6d16dc-ffec-11e4-9daa-3137454ef4a3.png)

Задачи не могут быть НАСТОЛЬКО похожи.

**Comment by IsachenkoV** [comment]
2 человека не могут выбрать одну и ту же задачу и в ней написать очевидный свитч по строке?
Я не знаю, как доказать Вам, что я делал задачу самостоятельно, потому что не представляю иного решения) Можно, конечно написать весь код в main-е, или вместо свитча использовать много ифов, но суть решения не изменится.

**Comment by pavel-b-novikov** [comment]
Дело не в свитче, а в одинаковой декомпозиции и одинаковом графе вызовов.

21 мая 2015 г., 20:01 пользователь Исаченко Владимир <
notifications@github.com> написал:

> 2 человека не могут выбрать одну и ту же задачу и в ней написать очевидный
> свитч по строке?
> Я не знаю, как доказать Вам, что я делал задачу самостоятельно)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IsachenkoV/nsudotnet/issues/1#issuecomment-104286328.

## 

Sincerelly yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by Serenitas** [comment]
Я могу честно признаться в одном - я услышала от Владимира, что он сделал два класса на encrypt и decrypt, мне показалось это решение логичным, и у себя я сделала так же. Остальной мой код - почти копия документации к какому-то из классов SymmetricAlgorithm с msdn (кажется, к RijndaelManaged) с необходимыми вставками вроде копирования потоков (про которое вы говорили на лекции). Если очень нужно, я могу попробовать придумать какое-нибудь другое разбиение задачи на классы, например, объединить функционал Encryptor`а и Decryptor`а в один класс, но имеющееся решение, повторюсь, кажется мне более логичным.

**Comment by pavel-b-novikov** [comment]
Про "по ссылке большая часть кода": по ссылке приводится пошаговое создание приложения для WindowsForms на основе шифрования, да еще и с поблочным копированием потоков, потому что stream.CopyTo появился только в версии .NET 4.0.
Это при условии что в вашем приложении не используется ни WindowsForms ни поблочное копирование.

**Comment by IsachenkoV** [comment]
Таки да, однако там же как шифровать и дешифровать файл, чем нам и нужно было заниматься в этой лабе. Если пофильтровать и смерджить с тем, что Вы показывали на лекции(то самое копирование потоков, например), то вот он результат.

**Comment by pavel-b-novikov** [comment]
Ай, черт с ним. Считайте что вам повезло.
