### ISSUE TITLE
[NumberGuesser] Списано?

### ISSUE THREAD

**Issue by pavel-b-novikov** [IsachenkoV/nsudotnet#2]
Слушайте, ну у вас определенно предельно похожий код со Стрекаловой.
Ребята, в чем дело? У нас же есть командные задачи. У нас стандартный алгоритм работы со списывателями - давать им несложную командную задачу.

**Comment by IsachenkoV** [comment]
Дело в том, что мы не списывали эти задачи друг у друга.
Эта задача на 1 балл, я не вижу смысла просто её списывать. Как и энигму, в которой 200 строк кода. Мы немного обсуждали энигму, когда я уже написал код и залил его на гитхаб, однако самого списывания не было, да и зачем, когда в ссылке, которую я приводил, написана уже большая часть кода.

**Comment by pavel-b-novikov** [comment]
Ладно, с NG черт с ним
