### ISSUE TITLE
[Enigma] Dispose

### ISSUE THREAD

**Issue by pavel-b-novikov** [IsachenkoV/nsudotnet#4]
Диспозится не все, что можно задиспозить. Исправьте.

**Comment by IsachenkoV** [comment]
А разве методы IO.File ReadAllLines/WriteAllLines не закрывают за собой все потоки?

**Comment by pavel-b-novikov** [comment]
Да здесь не в файлах дело.

**Comment by IsachenkoV** [comment]
А, кажется понял. Сам SymmetricAlgorithm нужно задиспозить

**Comment by pavel-b-novikov** [comment]
бинго

**Comment by IsachenkoV** [comment]
Исправил

**Comment by pavel-b-novikov** [comment]
Хоть бы кто додумался Dispose pattern реализовать в энкрипторах...
